jwt:
  secret: ${JWT_SECRET}
  zone: America/Guatemala
  access-token:
    expiration: 5
  refresh-token:
    expiration: 10_080

server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - ${VM_IP:http://localhost:4200}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowedHeaders:
                  - "*"
                maxAge: 3600
          routes:
            - id: auth-public-routes
              uri: ${AUTH_ROUTE_URI:http://localhost:8001}
              predicates:
                - Path=/v1/auth/**


            - id: user-public-routes
              uri: ${USER_ROUTE_URI:http://localhost:8002}
              predicates:
                - Path=/v1/users/{segment}
            - id: user-private-routes
              uri: ${USER_ROUTE_URI:http://localhost:8002}
              predicates:
                - Path=/v1/users/**
              filters:
                - JwtVerifyFilterFactory



            - id: client-public-routes
              uri: ${CLIENT_ROUTE_URI:http://localhost:8003}
              predicates:
                - Path=/v1/client/login
              filters:
                - JwtVerifyFilterFactory




